//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pivotDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Org_Child
    {
        public int Id { get; set; }
        public Nullable<int> ChildId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<System.DateTime> FirstAttendanceDate { get; set; }
        public Nullable<bool> NewFlagDone { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsLock { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual Org Org { get; set; }
    }
}
