//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajax_Example
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseInstructor
    {
        public int CourseID { get; set; }
        public int PersonID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Person Person { get; set; }
    }
}
